"""
C-S-H transfer workflow entry point.

Validates the optimized interface force field on disordered C-S-H structures
generated by pyCSH at varying Ca/Si ratios. The charge parameters used here
are the unified values from Workflow 2 (charge unification), already embedded
in the force field files under config/.

The C-S-H structures are in the data/ subdirectory. Pre-computed results are
in summary_density.csv, summary_bulk_modulus.csv, and summary_deformation.csv.

Requirements:
    - LAMMPS with CLASS2 + KSPACE packages
    - PBS scheduler (uses qsub/qstat)
    - MDSetup package (pip install -e ../../src/mdsetup/)

Usage:
    cd workflows/03_csh_transfer/
    python main_csh.py
"""
from run_MD_sim_csh import MD_sim_csh

if __name__ == "__main__":
    # Run MD simulations for all C-S-H structures in data/
    # Results are written to runs/ and can be compared against
    # the pre-computed summaries (summary_*.csv)
    MD_sim_csh(optimizer='IFF')
